#!/usr/bin/env python3
"""Install sdpm support for Kiro CLI.

Idempotent installer that wires this repository checkout into Kiro CLI.

Kiro can consume sdpm two ways, and they must not both be active:

* **power** — Kiro v3 loads the repository root as a Power (Agent Plugins
  ``plugin.json`` + ``mcp.json`` + ``skills/``). Powers are installed from the
  Kiro IDE; this script never installs one. It only audits that no legacy
  wiring is left behind to shadow it.
* **legacy** — Kiro v2 has no plugin mechanism, so the skills are symlinked
  into ``<KIRO_HOME>/skills/``, a dedicated composer agent is generated at
  ``<KIRO_HOME>/agents/sdpm-composer.json``, and the MCP server is registered
  in ``<KIRO_HOME>/settings/mcp.json``.

Everything this script writes is *owned*: it records nothing outside
``KIRO_HOME`` and it refuses to touch wiring that belongs to a different
checkout. If another checkout owns the ``sdpm`` MCP registration, a skill
symlink, or the composer agent, the run fails with a report instead of
overwriting it — pass ``--replace-existing`` to take it over deliberately.

Set ``KIRO_HOME`` (or pass ``--kiro-home``) to target a profile other than
``~/.kiro``; that is the only way to keep a v2 install and a v3 Power install
from colliding, because Powers are global-scope only.

The repository stays the single source of truth: mode behavior lives in
``personas/*.md`` and is served by the MCP server via
``start_presentation(mode=...)``. The generated composer agent carries no
behavior either — its prompt is a ``file://`` pointer into
``personas/composer.md`` (self-spawn remains the documented fallback for
environments without it). ``git pull`` updates take effect without re-running
this script. Re-run only if you move the checkout.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent

MCP_SERVER_NAME = "sdpm"

# Ownership of an existing artifact, relative to THIS checkout.
OWN = "own"  # generated by us, for this checkout, and still correct
STALE = "stale"  # our generated form, but its target no longer exists (moved checkout)
FOREIGN = "foreign"  # our generated form, owned by a different live checkout
UNKNOWN = "unknown"  # not a form we generate (hand-written, edited, unreadable)
ABSENT = "absent"  # nothing there

BLOCKING = (FOREIGN, UNKNOWN)


def info(msg: str) -> None:
    print(f"  {msg}")


def warn(msg: str) -> None:
    print(f"  WARNING: {msg}", file=sys.stderr)


def default_kiro_home() -> Path:
    """Kiro's global directory, honouring the ``KIRO_HOME`` override.

    Kiro relocates agents, skills, steering, settings and sessions together
    when ``KIRO_HOME`` is set, so an installer that hardcodes ``~/.kiro``
    writes into the wrong profile.
    """
    env = os.environ.get("KIRO_HOME")
    return Path(env).expanduser() if env else Path.home() / ".kiro"


def mcp_dir(repo_root: Path = REPO_ROOT) -> Path:
    return repo_root / "servers" / "local"


def plugin_name(repo_root: Path = REPO_ROOT) -> str | None:
    """Name declared by the portable Agent Plugins manifest, if present."""
    try:
        data = json.loads((repo_root / "plugin.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    name = data.get("name")
    return name if isinstance(name, str) else None


def repo_skill_names(repo_root: Path = REPO_ROOT) -> list[str]:
    """Skill directories shipped by this checkout (``skills/<name>/SKILL.md``)."""
    skills_root = repo_root / "skills"
    if not skills_root.is_dir():
        return []
    return sorted(p.name for p in skills_root.iterdir() if (p / "SKILL.md").is_file())


# --------------------------------------------------------------------------
# Audit — classify what is already installed before writing anything
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class Finding:
    kind: str  # "mcp" | "skill" | "composer"
    target: Path  # where the artifact lives
    status: str
    detail: str = ""

    def __str__(self) -> str:
        suffix = f" — {self.detail}" if self.detail else ""
        return f"{self.kind}: {self.target} [{self.status}]{suffix}"


def _expected_mcp_args(repo_root: Path) -> list[str]:
    return ["run", "--directory", str(mcp_dir(repo_root)), "python", "server.py"]


def _generated_mcp_directory(server: object) -> Path | None:
    """Recover the checkout directory from an entry in our generated form.

    Returns ``None`` for anything we would not have written, so hand-written
    entries are never mistaken for ours.
    """
    if not isinstance(server, dict) or server.get("command") != "uv":
        return None
    args = [str(a) for a in server.get("args", [])]
    # ["run", "--directory", <dir>, "python", "server.py"] — the shape every
    # sdpm installer and plugin manifest has used.
    if len(args) != 5 or args[0] != "run" or args[1] != "--directory":
        return None
    if args[3] != "python" or args[4] != "server.py":
        return None
    directory = Path(args[2])
    return directory if directory.is_absolute() else None


def audit_mcp(config_path: Path, repo_root: Path = REPO_ROOT) -> Finding:
    """Classify the ``sdpm`` MCP registration in ``config_path``."""
    if not config_path.exists():
        return Finding("mcp", config_path, ABSENT)
    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return Finding("mcp", config_path, UNKNOWN, "config file is not readable as JSON")
    server = data.get("mcpServers", {}).get(MCP_SERVER_NAME) if isinstance(data, dict) else None
    if server is None:
        return Finding("mcp", config_path, ABSENT)

    directory = _generated_mcp_directory(server)
    if directory is None:
        return Finding("mcp", config_path, UNKNOWN, f"'{MCP_SERVER_NAME}' entry is not in the generated form")
    if directory == mcp_dir(repo_root):
        return Finding("mcp", config_path, OWN)
    if directory.exists():
        return Finding("mcp", config_path, FOREIGN, f"registered to a live checkout at {directory}")
    return Finding("mcp", config_path, STALE, f"points at {directory}, which no longer exists")


def audit_skill_link(link: Path, repo_root: Path = REPO_ROOT) -> Finding:
    """Classify one ``<KIRO_HOME>/skills/<name>`` entry."""
    if not link.is_symlink():
        if link.exists():
            return Finding("skill", link, UNKNOWN, "exists but is not a symlink")
        return Finding("skill", link, ABSENT)

    target = link.resolve()
    if target == (repo_root / "skills" / link.name).resolve():
        return Finding("skill", link, OWN)
    # Our generated form always points at <checkout>/skills/<same name>.
    if target.parent.name == "skills" and target.name == link.name:
        if target.exists():
            return Finding("skill", link, FOREIGN, f"links into a live checkout at {target}")
        return Finding("skill", link, STALE, f"dangling link to {target}")
    return Finding("skill", link, UNKNOWN, f"links to {target}")


def _expected_composer_config(checkout: Path) -> dict:
    """The composer agent config this installer generates for ``checkout``.

    Same object the v0.5.0–v0.5.2 installers wrote (the deleted
    ``sdpm-composer.json.tmpl`` with ``{{CHECKOUT}}`` resolved), kept verbatim
    so ownership classification can require FULL equality across versions.

    Why a dedicated agent: compose is a fan-out workload (up to 10 parallel
    workers). The persona's self-spawn fallback works, but a general-purpose
    worker inherits every MCP server in the profile — each worker cold-starts
    all of them, and under parallel load the sdpm server can miss its init
    timeout on some workers (observed in practice). This agent gives workers
    the sdpm server only, with a generous timeout and pre-approved tools, and
    carries no behavior text: the prompt is a ``file://`` pointer into
    ``personas/composer.md``.
    """
    return {
        "name": "sdpm-composer",
        "description": (
            "sdpm slide composer (dispatched by the sdpm-vibe skill). "
            "Composes assigned slides from approved specs via the sdpm MCP server. "
            "No user interaction."
        ),
        "prompt": f"file://{checkout}/personas/composer.md",
        "mcpServers": {
            "sdpm": {
                "command": "uv",
                "args": [
                    "run",
                    "--directory",
                    f"{checkout}/servers/local",
                    "python",
                    "server.py",
                ],
                "timeout": 120000,
            }
        },
        "tools": ["read", "glob", "grep", "@sdpm"],
        "allowedTools": ["read", "glob", "grep", "@sdpm"],
        "useLegacyMcpJson": False,
    }


def generated_composer_checkout(data: object) -> Path | None:
    """Checkout that ``data`` was generated for, or ``None`` if we did not write it.

    The checkout root is recovered from the ``prompt`` field, then the whole
    object must equal the known generated form for that root (prompt and MCP
    args therefore must point at the SAME root). Any user edit — description,
    timeout, tools, extra fields — breaks equality, so the file is treated as
    unknown and left alone.
    """
    if not isinstance(data, dict):
        return None
    prompt = data.get("prompt")
    if not isinstance(prompt, str):
        return None
    prefix, suffix = "file://", "/personas/composer.md"
    if not (prompt.startswith(prefix) and prompt.endswith(suffix)):
        return None
    checkout = Path(prompt[len(prefix) : -len(suffix)])
    if not checkout.is_absolute():
        return None
    return checkout if data == _expected_composer_config(checkout) else None


def audit_composer(agents_dest: Path, repo_root: Path = REPO_ROOT) -> Finding:
    """Classify the generated ``sdpm-composer.json``.

    Legacy mode (re)generates this file; power mode removes it. Either way the
    decision is ownership-gated: a config belonging to another checkout is that
    checkout's business, even though it matches a form we recognise, and a
    user-edited one is never touched.
    """
    legacy = agents_dest / "sdpm-composer.json"
    if not legacy.exists():
        return Finding("composer", legacy, ABSENT)
    try:
        data = json.loads(legacy.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return Finding("composer", legacy, UNKNOWN, "not readable as JSON")
    checkout = generated_composer_checkout(data)
    if checkout is None:
        return Finding("composer", legacy, UNKNOWN, "does not match the known generated form")
    if checkout == repo_root:
        return Finding("composer", legacy, OWN)
    if checkout.exists():
        return Finding("composer", legacy, FOREIGN, f"generated for a live checkout at {checkout}")
    return Finding("composer", legacy, STALE, f"generated for {checkout}, which no longer exists")


def find_installed_power(kiro_home: Path, name: str | None) -> Path | None:
    """Best-effort lookup of an installed Power declaring ``name``.

    Advisory only. The on-disk layout under ``<KIRO_HOME>/powers/`` is not part
    of any published contract, a manifest on disk does not mean the Power is
    enabled, and an agent-scoped install may not include it at all. Never let
    this decide whether legacy wiring is safe to write — that is what the
    audit is for.
    """
    if name is None:
        return None
    powers_dir = kiro_home / "powers"
    if not powers_dir.is_dir():
        return None
    for manifest in sorted([*powers_dir.glob("*/plugin.json"), *powers_dir.glob("*/*/plugin.json")]):
        try:
            data = json.loads(manifest.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if isinstance(data, dict) and data.get("name") == name:
            return manifest.parent
    return None


def audit_existing(
    kiro_home: Path,
    repo_root: Path = REPO_ROOT,
    agent: str | None = None,
) -> list[Finding]:
    """Classify every artifact this installer could write."""
    agents_dest = kiro_home / "agents"
    config_path = agents_dest / f"{agent}.json" if agent else kiro_home / "settings" / "mcp.json"
    findings = [audit_mcp(config_path, repo_root)]
    skills_dest = kiro_home / "skills"
    for name in repo_skill_names(repo_root):
        findings.append(audit_skill_link(skills_dest / name, repo_root))
    findings.append(audit_composer(agents_dest, repo_root))
    return findings


# --------------------------------------------------------------------------
# Write operations — each one only touches artifacts we own
# --------------------------------------------------------------------------


def link_skills(kiro_home: Path, findings: list[Finding], repo_root: Path = REPO_ROOT) -> None:
    """Symlink this checkout's skills into ``<KIRO_HOME>/skills/`` (idempotent)."""
    skills_dest = kiro_home / "skills"
    skills_dest.mkdir(parents=True, exist_ok=True)
    for f in findings:
        if f.kind != "skill":
            continue
        source = repo_root / "skills" / f.target.name
        if f.status == OWN:
            info(f"{f.target} -> {source} (already linked)")
            continue
        if f.status in BLOCKING:
            continue  # reported by the caller; never overwritten here
        if f.target.is_symlink():
            f.target.unlink()
        f.target.symlink_to(source, target_is_directory=True)
        info(f"{f.target} -> {source} ({'relinked' if f.status == STALE else 'linked'})")


def remove_owned_composer_agent(findings: list[Finding]) -> None:
    """Delete the composer agent config, but only if we generated it.

    Used in power mode: the Power supersedes all legacy v2 wiring, including
    the composer agent.
    """
    for f in findings:
        if f.kind != "composer":
            continue
        if f.status in (OWN, STALE):
            f.target.unlink()
            info(f"{f.target} (removed composer agent — the Power supersedes it)")
        elif f.status == UNKNOWN:
            warn(
                f"{f.target} {f.detail} — left in place (it may be user-edited). "
                "Remove it manually when convenient."
            )


def write_composer_agent(findings: list[Finding], repo_root: Path = REPO_ROOT) -> None:
    """(Re)generate ``sdpm-composer.json`` for this checkout (idempotent).

    A registered ``sdpm-composer`` agent is the persona's preferred worker for
    parallel compose; without it, workers fall back to a general-purpose agent
    that cold-starts every MCP server in the profile per worker (see
    ``_expected_composer_config`` for the failure mode this avoids).
    """
    for f in findings:
        if f.kind != "composer":
            continue
        if f.status == OWN:
            info(f"{f.target} (already up to date)")
            continue
        if f.status in BLOCKING:
            continue  # reported by the caller; never overwritten here
        f.target.parent.mkdir(parents=True, exist_ok=True)
        f.target.write_text(
            json.dumps(_expected_composer_config(repo_root), indent=2) + "\n",
            encoding="utf-8",
        )
        info(f"{f.target} ({'regenerated' if f.status == STALE else 'generated'})")


def _kiro_env(kiro_home: Path) -> dict[str, str]:
    """Environment for ``kiro-cli`` calls.

    ``kiro-cli mcp add --scope global`` resolves "global" from its own
    ``KIRO_HOME``, so passing ``--kiro-home`` here without exporting it would
    write into the default profile instead of the requested one.
    """
    return {**os.environ, "KIRO_HOME": str(kiro_home)}


def register_mcp_server(
    kiro_cli: str | None,
    finding: Finding,
    agent: str | None,
    kiro_home: Path,
    repo_root: Path = REPO_ROOT,
) -> None:
    """Register the sdpm MCP server via ``kiro-cli mcp add`` (idempotent)."""
    if finding.status == OWN:
        info(f"'{MCP_SERVER_NAME}' already registered in {finding.target} (skipped)")
        return
    if finding.status in BLOCKING:
        return  # reported by the caller
    if kiro_cli is None:
        warn(
            "kiro-cli not found on PATH — skipped MCP registration. "
            "Install Kiro CLI and re-run `make install-kiro`."
        )
        return

    replacing = finding.status != ABSENT
    cmd = [
        kiro_cli,
        "mcp",
        "add",
        "--name",
        MCP_SERVER_NAME,
        "--command",
        "uv",
        "--args",
        json.dumps(_expected_mcp_args(repo_root)),
        "--timeout",
        "120000",
    ]
    if replacing:
        cmd.append("--force")
    cmd += ["--agent", agent] if agent else ["--scope", "global"]
    result = subprocess.run(cmd, capture_output=True, text=True, env=_kiro_env(kiro_home))
    if result.returncode != 0:
        warn(f"`{' '.join(cmd)}` failed:\n{result.stderr.strip() or result.stdout.strip()}")
        return
    info(f"'{MCP_SERVER_NAME}' {'updated' if replacing else 'registered'} in {finding.target}")


def unregister_mcp_server(
    kiro_cli: str | None,
    finding: Finding,
    agent: str | None,
    kiro_home: Path,
) -> None:
    """Drop an sdpm MCP registration we own (used when switching to a Power)."""
    if finding.status not in (OWN, STALE):
        return
    if kiro_cli is None:
        warn(
            f"kiro-cli not found on PATH — '{MCP_SERVER_NAME}' is still registered in "
            f"{finding.target} and would shadow the Power's own MCP server."
        )
        return
    cmd = [kiro_cli, "mcp", "remove", "--name", MCP_SERVER_NAME]
    cmd += ["--agent", agent] if agent else ["--scope", "global"]
    result = subprocess.run(cmd, capture_output=True, text=True, env=_kiro_env(kiro_home))
    if result.returncode != 0:
        warn(f"`{' '.join(cmd)}` failed:\n{result.stderr.strip() or result.stdout.strip()}")
        return
    info(f"'{MCP_SERVER_NAME}' removed from {finding.target} (the Power provides its own)")


def unlink_owned_skills(findings: list[Finding]) -> None:
    """Remove skill symlinks we own (the Power ships the same skills)."""
    for f in findings:
        if f.kind == "skill" and f.status in (OWN, STALE):
            f.target.unlink()
            info(f"{f.target} (removed — the Power provides this skill)")


# --------------------------------------------------------------------------


def report_conflicts(conflicts: list[Finding], replace_existing: bool) -> None:
    print("\nRefusing to continue — existing sdpm wiring is not owned by this checkout:")
    for f in conflicts:
        print(f"  - {f}")
    print(
        "\nAnother checkout is probably installed and in use. Options:\n"
        "  * install this checkout into a separate profile:\n"
        "      KIRO_HOME=~/.kiro-sdpm-dev make install-kiro\n"
        "  * remove the other checkout's wiring yourself, then re-run\n"
        + (
            "  * pass --replace-existing to take over the entries marked "
            "'foreign' (entries marked 'unknown' are never replaced)\n"
            if not replace_existing
            else "  * entries marked 'unknown' are never replaced automatically\n"
        )
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--mode",
        choices=("auto", "legacy", "power"),
        default="auto",
        help=(
            "auto (default): detect an installed Power and pick a mode, but audit either way. "
            "legacy: wire up Kiro v2 (skill symlinks + MCP registration). "
            "power: assume Kiro v3 loads this checkout as a Power and remove our legacy wiring."
        ),
    )
    parser.add_argument(
        "--agent",
        metavar="NAME",
        help=(
            "register the sdpm MCP server into <KIRO_HOME>/agents/NAME.json instead "
            "of the global <KIRO_HOME>/settings/mcp.json"
        ),
    )
    parser.add_argument(
        "--kiro-home",
        metavar="PATH",
        type=Path,
        default=None,
        help="Kiro global directory to install into (default: $KIRO_HOME, else ~/.kiro)",
    )
    parser.add_argument(
        "--replace-existing",
        action="store_true",
        help="take over wiring owned by another live checkout (never applies to 'unknown' entries)",
    )
    opts = parser.parse_args(argv)

    kiro_home = (opts.kiro_home or default_kiro_home()).expanduser()
    print(f"Installing sdpm for Kiro CLI\n  checkout:  {REPO_ROOT}\n  KIRO_HOME: {kiro_home}\n")

    kiro_cli = shutil.which("kiro-cli")
    if kiro_cli is None:
        warn("kiro-cli not found on PATH — MCP registration will be skipped.")

    findings = audit_existing(kiro_home, REPO_ROOT, opts.agent)

    name = plugin_name(REPO_ROOT)
    power = find_installed_power(kiro_home, name)
    mode = opts.mode
    if mode == "auto":
        mode = "power" if power is not None else "legacy"
        if power is not None:
            info(
                f"Power '{name}' found at {power} — assuming mode=power. "
                "Presence on disk does not prove it is enabled; pass --mode legacy to override."
            )
        else:
            info(f"No installed Power named '{name}' under {kiro_home / 'powers'} — assuming mode=legacy.")
    print()

    conflicts = [f for f in findings if f.status in BLOCKING]
    if opts.replace_existing:
        conflicts = [f for f in conflicts if f.status != FOREIGN]
        findings = [
            Finding(f.kind, f.target, STALE, f"taken over ({f.detail})") if f.status == FOREIGN else f
            for f in findings
        ]
    if conflicts:
        report_conflicts(conflicts, opts.replace_existing)
        return 1

    mcp_finding = next(f for f in findings if f.kind == "mcp")
    if mode == "power":
        print("[1/2] Removing legacy Kiro v2 wiring (the Power supersedes it)")
        unlink_owned_skills(findings)
        remove_owned_composer_agent(findings)
        print("[2/2] Checking the MCP registration")
        unregister_mcp_server(kiro_cli, mcp_finding, opts.agent, kiro_home)
        print(
            "\nDone. The Power provides the skills and its MCP server is managed by Kiro.\n"
            "Start a NEW session and ask for slides."
        )
        return 0

    print(f"[1/3] Linking skills into {kiro_home / 'skills'}")
    link_skills(kiro_home, findings, REPO_ROOT)
    print(f"[2/3] Registering the composer agent in {kiro_home / 'agents'}")
    write_composer_agent(findings, REPO_ROOT)
    print(f"[3/3] Registering MCP server '{MCP_SERVER_NAME}' in {mcp_finding.target}")
    register_mcp_server(kiro_cli, mcp_finding, opts.agent, kiro_home, REPO_ROOT)

    print(
        "\nDone. Usage:\n"
        "  1. Make sure `uv` and LibreOffice/poppler are installed (previews need them).\n"
        "  2. Start a NEW session: kiro-cli chat\n"
        '  3. Ask for slides, e.g. "このURLをスライドにして https://..." — or run /sdpm-vibe,\n'
        "     /sdpm-spec, /sdpm-style to pick a mode explicitly.\n"
        "\n"
        "Updates: `git pull` in this checkout is enough. Re-run `make install-kiro`\n"
        "only if you move the checkout."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
