# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
"""Tests for the Kiro installer's ownership rules and install modes.

The installer writes into a Kiro profile that other checkouts may share, so
every artifact it could touch is classified first:

* ``own``     — generated by this checkout, still correct
* ``stale``   — our generated form, but its target is gone (moved checkout)
* ``foreign`` — our generated form, owned by a different *live* checkout
* ``unknown`` — not a form we generate (hand-written or user-edited)
* ``absent``  — nothing there

Only ``own``/``stale``/``absent`` are written. ``foreign`` requires
``--replace-existing``; ``unknown`` is never touched. This is what keeps
``make install-kiro`` in one checkout from hijacking another checkout's
working install.

Every test runs against a temporary ``KIRO_HOME`` and never invokes
``kiro-cli``.
"""

import importlib.util
import json
import os
import sys
from pathlib import Path

import pytest

_INSTALL_PY = Path(__file__).resolve().parent.parent / "clients" / "kiro" / "install.py"
_spec = importlib.util.spec_from_file_location("kiro_install", _INSTALL_PY)
kiro_install = importlib.util.module_from_spec(_spec)
# dataclasses resolves annotations through sys.modules[cls.__module__]
sys.modules["kiro_install"] = kiro_install
_spec.loader.exec_module(kiro_install)

REPO_ROOT = kiro_install.REPO_ROOT
OWN = kiro_install.OWN
STALE = kiro_install.STALE
FOREIGN = kiro_install.FOREIGN
UNKNOWN = kiro_install.UNKNOWN
ABSENT = kiro_install.ABSENT


@pytest.fixture
def kiro_home(tmp_path):
    """An empty Kiro profile."""
    home = tmp_path / "kiro"
    for sub in ("agents", "skills", "settings"):
        (home / sub).mkdir(parents=True)
    return home


@pytest.fixture
def live_checkout(tmp_path):
    """A different checkout that exists on disk (so it counts as ``foreign``)."""
    other = tmp_path / "other-checkout"
    (other / "servers" / "local").mkdir(parents=True)
    for name in ("sdpm-vibe", "sdpm-spec", "sdpm-style"):
        (other / "skills" / name).mkdir(parents=True)
    (other / "personas").mkdir()
    return other


@pytest.fixture
def no_kiro_cli(monkeypatch):
    """Make ``kiro-cli`` look absent so no subprocess is ever spawned."""
    monkeypatch.setattr(kiro_install.shutil, "which", lambda _name: None)


def _write_mcp(config_path: Path, directory: Path, **overrides) -> None:
    server = {
        "command": "uv",
        "args": ["run", "--directory", str(directory), "python", "server.py"],
    }
    server.update(overrides)
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(json.dumps({"mcpServers": {"sdpm": server}}), encoding="utf-8")


def _write_composer(agents_dir: Path, config) -> Path:
    p = agents_dir / "sdpm-composer.json"
    p.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    return p


class TestKiroHomeResolution:
    def test_uses_kiro_home_env_var(self, monkeypatch, tmp_path):
        monkeypatch.setenv("KIRO_HOME", str(tmp_path / "profile"))
        assert kiro_install.default_kiro_home() == tmp_path / "profile"

    def test_expands_tilde(self, monkeypatch):
        monkeypatch.setenv("KIRO_HOME", "~/somewhere")
        assert kiro_install.default_kiro_home() == Path.home() / "somewhere"

    def test_falls_back_to_dot_kiro(self, monkeypatch):
        monkeypatch.delenv("KIRO_HOME", raising=False)
        assert kiro_install.default_kiro_home() == Path.home() / ".kiro"


class TestAuditMcp:
    def test_absent_when_no_config(self, kiro_home):
        f = kiro_install.audit_mcp(kiro_home / "settings" / "mcp.json")
        assert f.status == ABSENT

    def test_absent_when_other_servers_only(self, kiro_home):
        cfg = kiro_home / "settings" / "mcp.json"
        cfg.write_text(json.dumps({"mcpServers": {"other": {"command": "x"}}}), encoding="utf-8")
        assert kiro_install.audit_mcp(cfg).status == ABSENT

    def test_own_when_pointing_at_this_checkout(self, kiro_home):
        cfg = kiro_home / "settings" / "mcp.json"
        _write_mcp(cfg, REPO_ROOT / "servers" / "local")
        assert kiro_install.audit_mcp(cfg).status == OWN

    def test_foreign_when_pointing_at_a_live_checkout(self, kiro_home, live_checkout):
        cfg = kiro_home / "settings" / "mcp.json"
        _write_mcp(cfg, live_checkout / "servers" / "local")
        f = kiro_install.audit_mcp(cfg)
        assert f.status == FOREIGN
        assert str(live_checkout) in f.detail

    def test_stale_when_target_no_longer_exists(self, kiro_home, tmp_path):
        # The documented repair path: move the checkout, re-run the installer.
        cfg = kiro_home / "settings" / "mcp.json"
        _write_mcp(cfg, tmp_path / "moved-away" / "servers" / "local")
        assert kiro_install.audit_mcp(cfg).status == STALE

    @pytest.mark.parametrize(
        "server",
        [
            {"command": "python", "args": ["run", "--directory", "/x", "python", "server.py"]},
            {"command": "uv", "args": ["run", "/x/servers/local"]},
            {"command": "uv", "args": ["run", "--directory", "relative/path", "python", "server.py"]},
            {"command": "uv", "args": ["run", "--directory", "/x", "python", "other.py"]},
            {"url": "https://example.invalid/mcp"},
        ],
        ids=["other-command", "short-args", "relative-dir", "other-script", "remote"],
    )
    def test_unknown_for_hand_written_entries(self, kiro_home, server):
        cfg = kiro_home / "settings" / "mcp.json"
        cfg.write_text(json.dumps({"mcpServers": {"sdpm": server}}), encoding="utf-8")
        assert kiro_install.audit_mcp(cfg).status == UNKNOWN

    def test_unknown_when_config_is_not_json(self, kiro_home):
        cfg = kiro_home / "settings" / "mcp.json"
        cfg.write_text("{not json", encoding="utf-8")
        assert kiro_install.audit_mcp(cfg).status == UNKNOWN

    def test_agent_scope_reads_the_agent_config(self, kiro_home, live_checkout):
        cfg = kiro_home / "agents" / "myagent.json"
        _write_mcp(cfg, live_checkout / "servers" / "local")
        findings = kiro_install.audit_existing(kiro_home, REPO_ROOT, agent="myagent")
        mcp = next(f for f in findings if f.kind == "mcp")
        assert (mcp.target, mcp.status) == (cfg, FOREIGN)


class TestAuditSkillLink:
    def test_absent(self, kiro_home):
        assert kiro_install.audit_skill_link(kiro_home / "skills" / "sdpm-vibe").status == ABSENT

    def test_own(self, kiro_home):
        link = kiro_home / "skills" / "sdpm-vibe"
        link.symlink_to(REPO_ROOT / "skills" / "sdpm-vibe")
        assert kiro_install.audit_skill_link(link).status == OWN

    def test_own_through_a_symlinked_home(self, kiro_home, tmp_path):
        # /home/<user> is often itself a symlink; comparison must be on
        # resolved paths or every link looks foreign.
        alias = tmp_path / "alias"
        alias.symlink_to(REPO_ROOT)
        link = kiro_home / "skills" / "sdpm-vibe"
        link.symlink_to(alias / "skills" / "sdpm-vibe")
        assert kiro_install.audit_skill_link(link).status == OWN

    def test_foreign_when_linked_into_a_live_checkout(self, kiro_home, live_checkout):
        link = kiro_home / "skills" / "sdpm-vibe"
        link.symlink_to(live_checkout / "skills" / "sdpm-vibe")
        assert kiro_install.audit_skill_link(link).status == FOREIGN

    def test_stale_when_dangling(self, kiro_home, tmp_path):
        link = kiro_home / "skills" / "sdpm-vibe"
        link.symlink_to(tmp_path / "gone" / "skills" / "sdpm-vibe")
        assert kiro_install.audit_skill_link(link).status == STALE

    def test_unknown_when_a_real_directory(self, kiro_home):
        d = kiro_home / "skills" / "sdpm-vibe"
        d.mkdir()
        (d / "SKILL.md").write_text("---\nname: sdpm-vibe\n---\n", encoding="utf-8")
        assert kiro_install.audit_skill_link(d).status == UNKNOWN

    def test_unknown_when_linked_somewhere_unrelated(self, kiro_home, tmp_path):
        target = tmp_path / "elsewhere"
        target.mkdir()
        link = kiro_home / "skills" / "sdpm-vibe"
        link.symlink_to(target)
        assert kiro_install.audit_skill_link(link).status == UNKNOWN


class TestAuditComposer:
    """Legacy mode (re)generates the composer agent, power mode removes it —
    both are ownership decisions driven by this classification."""

    def test_absent(self, kiro_home):
        assert kiro_install.audit_composer(kiro_home / "agents").status == ABSENT

    def test_own_for_this_checkout(self, kiro_home):
        _write_composer(kiro_home / "agents", kiro_install._expected_composer_config(REPO_ROOT))
        assert kiro_install.audit_composer(kiro_home / "agents").status == OWN

    def test_formatting_differences_do_not_matter(self, kiro_home):
        p = kiro_home / "agents" / "sdpm-composer.json"
        p.write_text(json.dumps(kiro_install._expected_composer_config(REPO_ROOT)), encoding="utf-8")
        assert kiro_install.audit_composer(kiro_home / "agents").status == OWN

    def test_foreign_for_another_live_checkout(self, kiro_home, live_checkout):
        _write_composer(kiro_home / "agents", kiro_install._expected_composer_config(live_checkout))
        assert kiro_install.audit_composer(kiro_home / "agents").status == FOREIGN

    def test_stale_for_a_checkout_that_is_gone(self, kiro_home, tmp_path):
        gone = tmp_path / "gone" / "checkout"
        _write_composer(kiro_home / "agents", kiro_install._expected_composer_config(gone))
        assert kiro_install.audit_composer(kiro_home / "agents").status == STALE

    @pytest.mark.parametrize(
        "mutate",
        [
            lambda c: c.update(description="MY CUSTOM DESCRIPTION"),
            lambda c: c.update(tools=["read", "glob", "grep", "@sdpm", "shell"]),
            lambda c: c["mcpServers"]["sdpm"].update(timeout=999),
            lambda c: c["mcpServers"]["sdpm"].update(env={"FOO": "1"}),
            lambda c: c.update(useLegacyMcpJson=True),
            lambda c: c.update(model="my-model"),
            lambda c: c.update(mcpServers={"sdpm": None}),
        ],
        ids=["description", "tools", "timeout", "extra-mcp-field", "useLegacyMcpJson", "extra-field", "null-server"],
    )
    def test_unknown_for_any_user_edit(self, kiro_home, mutate):
        cfg = kiro_install._expected_composer_config(REPO_ROOT)
        mutate(cfg)
        _write_composer(kiro_home / "agents", cfg)
        assert kiro_install.audit_composer(kiro_home / "agents").status == UNKNOWN

    def test_unknown_when_prompt_and_mcp_roots_disagree(self, kiro_home, tmp_path):
        cfg = kiro_install._expected_composer_config(REPO_ROOT)
        cfg["prompt"] = f"file://{tmp_path}/other/personas/composer.md"
        _write_composer(kiro_home / "agents", cfg)
        assert kiro_install.audit_composer(kiro_home / "agents").status == UNKNOWN

    def test_unknown_when_unparseable(self, kiro_home):
        (kiro_home / "agents" / "sdpm-composer.json").write_text("{not json", encoding="utf-8")
        assert kiro_install.audit_composer(kiro_home / "agents").status == UNKNOWN


class TestPowerDetectionIsAdvisory:
    def test_none_when_no_powers_dir(self, kiro_home):
        assert kiro_install.find_installed_power(kiro_home, "spec-driven-presentation-maker") is None

    def test_matches_on_manifest_name_not_directory_name(self, kiro_home):
        # The on-disk layout under powers/ is not a published contract, so the
        # manifest name is the only thing we may key on.
        d = kiro_home / "powers" / "some-opaque-dir-name"
        d.mkdir(parents=True)
        (d / "plugin.json").write_text(json.dumps({"name": "spec-driven-presentation-maker"}), encoding="utf-8")
        assert kiro_install.find_installed_power(kiro_home, "spec-driven-presentation-maker") == d

    def test_ignores_other_plugins(self, kiro_home):
        d = kiro_home / "powers" / "unrelated"
        d.mkdir(parents=True)
        (d / "plugin.json").write_text(json.dumps({"name": "something-else"}), encoding="utf-8")
        assert kiro_install.find_installed_power(kiro_home, "spec-driven-presentation-maker") is None

    def test_survives_a_broken_manifest(self, kiro_home):
        broken = kiro_home / "powers" / "broken"
        broken.mkdir(parents=True)
        (broken / "plugin.json").write_text("{not json", encoding="utf-8")
        good = kiro_home / "powers" / "good"
        good.mkdir(parents=True)
        (good / "plugin.json").write_text(json.dumps({"name": "spec-driven-presentation-maker"}), encoding="utf-8")
        assert kiro_install.find_installed_power(kiro_home, "spec-driven-presentation-maker") == good


class TestMainRefusesForeignWiring:
    def test_exits_nonzero_and_writes_nothing(self, kiro_home, live_checkout, no_kiro_cli, capsys):
        cfg = kiro_home / "settings" / "mcp.json"
        _write_mcp(cfg, live_checkout / "servers" / "local")
        before = cfg.read_bytes()
        link = kiro_home / "skills" / "sdpm-vibe"
        link.symlink_to(live_checkout / "skills" / "sdpm-vibe")
        composer = _write_composer(
            kiro_home / "agents", kiro_install._expected_composer_config(live_checkout)
        )

        assert kiro_install.main(["--kiro-home", str(kiro_home)]) == 1

        assert cfg.read_bytes() == before
        assert link.resolve() == (live_checkout / "skills" / "sdpm-vibe").resolve()
        assert composer.exists()
        assert "Refusing to continue" in capsys.readouterr().out

    def test_replace_existing_takes_over_foreign_only(self, kiro_home, live_checkout, no_kiro_cli):
        link = kiro_home / "skills" / "sdpm-vibe"
        link.symlink_to(live_checkout / "skills" / "sdpm-vibe")

        assert kiro_install.main(["--kiro-home", str(kiro_home), "--replace-existing"]) == 0
        assert link.resolve() == (REPO_ROOT / "skills" / "sdpm-vibe").resolve()

    def test_replace_existing_never_takes_over_unknown(self, kiro_home, no_kiro_cli):
        d = kiro_home / "skills" / "sdpm-vibe"
        d.mkdir()
        (d / "SKILL.md").write_text("hand written", encoding="utf-8")

        assert kiro_install.main(["--kiro-home", str(kiro_home), "--replace-existing"]) == 1
        assert (d / "SKILL.md").read_text(encoding="utf-8") == "hand written"


class TestMainLegacyMode:
    def test_links_every_shipped_skill(self, kiro_home, no_kiro_cli):
        assert kiro_install.main(["--kiro-home", str(kiro_home), "--mode", "legacy"]) == 0
        for name in kiro_install.repo_skill_names():
            link = kiro_home / "skills" / name
            assert link.is_symlink()
            assert link.resolve() == (REPO_ROOT / "skills" / name).resolve()

    def test_is_idempotent(self, kiro_home, no_kiro_cli):
        assert kiro_install.main(["--kiro-home", str(kiro_home), "--mode", "legacy"]) == 0
        assert kiro_install.main(["--kiro-home", str(kiro_home), "--mode", "legacy"]) == 0
        for name in kiro_install.repo_skill_names():
            assert (kiro_home / "skills" / name).is_symlink()

    def test_repairs_a_dangling_link_from_a_moved_checkout(self, kiro_home, no_kiro_cli, tmp_path):
        link = kiro_home / "skills" / "sdpm-vibe"
        link.symlink_to(tmp_path / "gone" / "skills" / "sdpm-vibe")

        assert kiro_install.main(["--kiro-home", str(kiro_home), "--mode", "legacy"]) == 0
        assert link.resolve() == (REPO_ROOT / "skills" / "sdpm-vibe").resolve()

    def test_generates_the_composer_agent(self, kiro_home, no_kiro_cli):
        assert kiro_install.main(["--kiro-home", str(kiro_home), "--mode", "legacy"]) == 0
        composer = kiro_home / "agents" / "sdpm-composer.json"
        assert composer.exists()
        data = json.loads(composer.read_text(encoding="utf-8"))
        assert data == kiro_install._expected_composer_config(REPO_ROOT)
        # The generated config is a thin pointer: sdpm MCP only, behavior
        # served from personas/ — never inline.
        assert set(data["mcpServers"]) == {"sdpm"}
        assert data["prompt"].startswith("file://")
        assert data["prompt"].endswith("/personas/composer.md")

    def test_composer_generation_is_idempotent(self, kiro_home, no_kiro_cli):
        assert kiro_install.main(["--kiro-home", str(kiro_home), "--mode", "legacy"]) == 0
        composer = kiro_home / "agents" / "sdpm-composer.json"
        first = composer.read_text(encoding="utf-8")
        assert kiro_install.main(["--kiro-home", str(kiro_home), "--mode", "legacy"]) == 0
        assert composer.read_text(encoding="utf-8") == first

    def test_repairs_a_composer_agent_from_a_moved_checkout(
        self, kiro_home, no_kiro_cli, tmp_path
    ):
        gone = tmp_path / "moved-away"
        _write_composer(kiro_home / "agents", kiro_install._expected_composer_config(gone))

        assert kiro_install.main(["--kiro-home", str(kiro_home), "--mode", "legacy"]) == 0
        data = json.loads(
            (kiro_home / "agents" / "sdpm-composer.json").read_text(encoding="utf-8")
        )
        assert data == kiro_install._expected_composer_config(REPO_ROOT)

    def test_never_overwrites_a_user_edited_composer_agent(self, kiro_home, no_kiro_cli):
        cfg = kiro_install._expected_composer_config(REPO_ROOT)
        cfg["tools"] = ["*"]  # user customisation -> unknown
        composer = _write_composer(kiro_home / "agents", cfg)

        assert kiro_install.main(["--kiro-home", str(kiro_home), "--mode", "legacy"]) == 1
        assert json.loads(composer.read_text(encoding="utf-8")) == cfg

    def test_registers_mcp_with_this_checkouts_directory(self, kiro_home, monkeypatch):
        calls = []

        class _Result:
            returncode = 0
            stdout = ""
            stderr = ""

        monkeypatch.setattr(kiro_install.shutil, "which", lambda _n: "/usr/bin/kiro-cli")
        monkeypatch.setattr(
            kiro_install.subprocess,
            "run",
            lambda cmd, **kw: calls.append((cmd, kw)) or _Result(),
        )

        assert kiro_install.main(["--kiro-home", str(kiro_home), "--mode", "legacy"]) == 0
        cmd, kwargs = calls[0]
        assert cmd[1:3] == ["mcp", "add"]
        assert "--force" not in cmd
        assert json.loads(cmd[cmd.index("--args") + 1]) == [
            "run",
            "--directory",
            str(REPO_ROOT / "servers" / "local"),
            "python",
            "server.py",
        ]
        # kiro-cli resolves "global" from its own KIRO_HOME, so the child
        # process must inherit the profile we were asked to install into.
        assert kwargs["env"]["KIRO_HOME"] == str(kiro_home)


class TestMainPowerMode:
    def test_does_not_create_legacy_wiring(self, kiro_home, no_kiro_cli):
        assert kiro_install.main(["--kiro-home", str(kiro_home), "--mode", "power"]) == 0
        assert not any((kiro_home / "skills").iterdir())
        assert not (kiro_home / "settings" / "mcp.json").exists()

    def test_removes_our_own_legacy_wiring(self, kiro_home, no_kiro_cli):
        link = kiro_home / "skills" / "sdpm-vibe"
        link.symlink_to(REPO_ROOT / "skills" / "sdpm-vibe")
        composer = _write_composer(
            kiro_home / "agents", kiro_install._expected_composer_config(REPO_ROOT)
        )

        assert kiro_install.main(["--kiro-home", str(kiro_home), "--mode", "power"]) == 0
        assert not link.is_symlink()
        assert not composer.exists()

    def test_leaves_another_checkouts_wiring_alone_and_fails(self, kiro_home, live_checkout, no_kiro_cli):
        link = kiro_home / "skills" / "sdpm-vibe"
        link.symlink_to(live_checkout / "skills" / "sdpm-vibe")

        assert kiro_install.main(["--kiro-home", str(kiro_home), "--mode", "power"]) == 1
        assert link.resolve() == (live_checkout / "skills" / "sdpm-vibe").resolve()

    def test_auto_selects_power_when_a_manifest_is_installed(self, kiro_home, no_kiro_cli, capsys):
        d = kiro_home / "powers" / "installed-sdpm"
        d.mkdir(parents=True)
        (d / "plugin.json").write_text(
            json.dumps({"name": kiro_install.plugin_name()}), encoding="utf-8"
        )

        assert kiro_install.main(["--kiro-home", str(kiro_home)]) == 0
        out = capsys.readouterr().out
        assert "assuming mode=power" in out
        # Detection must be presented as advisory, never as proof.
        assert "does not prove it is enabled" in out
        assert not any((kiro_home / "skills").iterdir())


class TestNoWritesOutsideTheRequestedProfile:
    def test_real_kiro_home_env_is_not_consulted_when_flag_is_given(self, kiro_home, no_kiro_cli, monkeypatch, tmp_path):
        decoy = tmp_path / "decoy"
        decoy.mkdir()
        monkeypatch.setenv("KIRO_HOME", str(decoy))

        assert kiro_install.main(["--kiro-home", str(kiro_home), "--mode", "legacy"]) == 0
        assert not list(decoy.iterdir())
        assert (kiro_home / "skills" / "sdpm-vibe").is_symlink()

    def test_env_var_is_used_when_no_flag_is_given(self, kiro_home, no_kiro_cli, monkeypatch):
        monkeypatch.setenv("KIRO_HOME", str(kiro_home))
        assert kiro_install.main(["--mode", "legacy"]) == 0
        assert (kiro_home / "skills" / "sdpm-vibe").is_symlink()


class TestInstallerShape:
    def test_render_composer_agent_is_gone(self):
        assert not hasattr(kiro_install, "render_composer_agent")

    def test_template_file_is_gone(self):
        assert not (_INSTALL_PY.parent / "sdpm-composer.json.tmpl").exists()

    def test_kiro_home_is_not_hardcoded_at_import_time(self):
        # A module-level ``KIRO_HOME = Path.home() / ".kiro"`` cannot honour
        # the env var, and silently wrote into the default profile.
        assert not hasattr(kiro_install, "KIRO_HOME")

    def test_environ_is_read_lazily(self, monkeypatch, tmp_path):
        monkeypatch.setenv("KIRO_HOME", str(tmp_path / "late"))
        assert kiro_install.default_kiro_home() == tmp_path / "late"
        assert os.environ["KIRO_HOME"] == str(tmp_path / "late")
